name: run-cpt
author: Dmitry Arkhipov <grisumbras@gmail.com>
description: GitHub Action that runs conan_package_tools
branding:
  icon: package
  color: blue
inputs:
  build-script:
    description: Path to the build script
    required: false
    default: build.py
  install:
    description: what version of conan_package_tools to install
    required: false
    default: latest
runs:
  using: node12
  main: main.js
